import type { AidRequest, Shelter, Volunteer, Resource } from './types';

const now = Date.now();
const min = 60 * 1000;
const hr  = 60 * min;

// ─────────────────────────────────────────────────────────────────────────────
// REGION KEYS
// ─────────────────────────────────────────────────────────────────────────────
export type RegionKey = 'ncr' | 'badrinath';

// ─────────────────────────────────────────────────────────────────────────────
// NCR — YAMUNA BANK / DELHI
// ─────────────────────────────────────────────────────────────────────────────

const NCR_REQUESTS: AidRequest[] = [
  {
    id: 'req-001',
    category: 'medical',
    priority: 'critical',
    status: 'active',
    title: 'Dialysis patient stranded near Yamuna Bank',
    details: 'Elderly resident needs dialysis. Mayur Vihar clinic unreachable due to waterlogged roads. BP rising.',
    items: ['Dialysis transport', 'BP medication', 'Insulin (NovoRapid)'],
    contactName: 'Ramesh Verma',
    contactPhone: '+91 98xxx xx142',
    distanceMiles: 0.4,
    createdAt: now - 12 * min,
    coords: { x: 32, y: 28 },
    peopleCount: 1,
  },
  {
    id: 'req-002',
    category: 'rescue',
    priority: 'critical',
    status: 'active',
    title: 'Family trapped in flooded basement — Old Yamuna Bazar',
    details: 'Two adults, one child. Water entered basement near Chandni Chowk. No boat access yet.',
    items: ['Boat rescue', 'Life jackets (3)', 'Drinking water'],
    contactName: 'Imran Sheikh',
    contactPhone: '+91 98xxx xx188',
    distanceMiles: 0.8,
    createdAt: now - 4 * min,
    coords: { x: 58, y: 42 },
    peopleCount: 3,
  },
  {
    id: 'req-003',
    category: 'food',
    priority: 'urgent',
    status: 'active',
    title: 'Clean water for 48 residents at Geeta Colony camp',
    details: '12 families sheltering at Geeta Colony community hall. Tap water contaminated by flood seepage.',
    items: ['Bottled water (20+ jerrycans)', 'Water purification tablets', 'ORS sachets'],
    contactName: 'Priya Nair',
    contactPhone: '+91 98xxx xx231',
    distanceMiles: 1.2,
    createdAt: now - 38 * min,
    coords: { x: 44, y: 62 },
    peopleCount: 48,
  },
  {
    id: 'req-004',
    category: 'shelter',
    priority: 'urgent',
    status: 'active',
    title: 'Temporary shelter for 4 children — Shakarpur',
    details: 'Parents admitted to LNJP Hospital. Children ages 4–12 with neighbour. Need safe overnight shelter.',
    items: ['Temporary beds (4)', 'Blankets', 'Child clothing'],
    contactName: 'Sarla Devi',
    contactPhone: '+91 98xxx xx307',
    distanceMiles: 1.6,
    createdAt: now - 1.2 * hr,
    coords: { x: 70, y: 30 },
    peopleCount: 5,
  },
  {
    id: 'req-005',
    category: 'volunteers',
    priority: 'moderate',
    status: 'active',
    title: 'Sandbagging crew at Yamuna embankment — Wazirabad',
    details: 'Embankment holding but water rising. Need 10+ volunteers for 4-hour shift. NDRF coordinating.',
    items: ['Volunteers (10+)', 'Work gloves', 'Shovels', 'Sandbags'],
    contactName: 'Havildar R. Singh (NDRF)',
    contactPhone: '+91 98xxx xx410',
    distanceMiles: 1.9,
    createdAt: now - 2 * hr,
    coords: { x: 22, y: 70 },
    peopleCount: 0,
  },
  {
    id: 'req-006',
    category: 'medical',
    priority: 'urgent',
    status: 'active',
    title: 'Oxygen concentrator for COPD patient — Seelampur',
    details: 'Power out for 14 hours. Backup cylinder nearly empty. AIIMS trauma centre on standby.',
    items: ['Oxygen concentrator', 'Portable battery pack', 'Nebulizer'],
    contactName: 'David Khanna',
    contactPhone: '+91 98xxx xx522',
    distanceMiles: 0.6,
    createdAt: now - 25 * min,
    coords: { x: 50, y: 20 },
    peopleCount: 1,
  },
  {
    id: 'req-007',
    category: 'food',
    priority: 'moderate',
    status: 'active',
    title: 'Baby formula and diapers — Usmanpur riverside',
    details: 'Infant 4 months old. Family evacuated from Usmanpur with only essentials.',
    items: ['Formula (0–6mo)', 'Diapers (size 2)', 'Baby wipes', 'Cerelac'],
    contactName: 'Aisha Begum',
    contactPhone: '+91 98xxx xx633',
    distanceMiles: 1.1,
    createdAt: now - 55 * min,
    coords: { x: 76, y: 55 },
    peopleCount: 2,
  },
  {
    id: 'req-008',
    category: 'volunteers',
    priority: 'moderate',
    status: 'active',
    title: '4WD drivers for last-mile supply delivery — ITO',
    details: 'Delivering supplies to cut-off colonies near ITO and Raj Ghat. Fuel reimbursed by SDM office.',
    items: ['4WD drivers (5)', 'Valid DL', 'Local route knowledge'],
    contactName: 'Linda Pinto (SDM Office)',
    contactPhone: '+91 98xxx xx744',
    distanceMiles: 1.4,
    createdAt: now - 1.5 * hr,
    coords: { x: 38, y: 48 },
    peopleCount: 0,
  },
];

const NCR_SHELTERS: Shelter[] = [
  {
    id: 'shelter-001',
    name: 'Rajkiya Sarvodaya Bal Vidyalaya, Mayur Vihar',
    address: 'Pocket 1, Mayur Vihar Phase I, East Delhi',
    capacity: 60,
    occupied: 45,
    coords: { x: 28, y: 50 },
    amenities: ['Pet-friendly', 'Accessible', 'Hot meals (ISKCON)', 'Medical staff'],
    status: 'open',
  },
  {
    id: 'shelter-002',
    name: 'Talkatora Indoor Stadium',
    address: 'Willingdon Crescent, New Delhi',
    capacity: 120,
    occupied: 118,
    coords: { x: 64, y: 68 },
    amenities: ['Cots provided', 'Family rooms', 'Charging station'],
    status: 'full',
  },
  {
    id: 'shelter-003',
    name: 'Ramleela Ground, Red Fort',
    address: 'Chandni Chowk, Old Delhi',
    capacity: 40,
    occupied: 12,
    coords: { x: 82, y: 38 },
    amenities: ['Hot meals (Gurudwara)', 'Quiet space', 'Counseling'],
    status: 'open',
  },
  {
    id: 'shelter-004',
    name: 'Chhatrasal Stadium',
    address: 'Model Town, North Delhi',
    capacity: 200,
    occupied: 134,
    coords: { x: 16, y: 36 },
    amenities: ['Large capacity', 'Medical staff (GTB Hospital)', 'Pet-friendly', 'Showers'],
    status: 'open',
  },
];

const NCR_VOLUNTEERS: Volunteer[] = [
  {
    id: 'vol-001',
    name: 'Dr. Arjun R. (AIIMS, EMT)',
    skills: ['Medical', 'First aid', 'Triage'],
    coords: { x: 40, y: 35 },
    distanceMiles: 0.5,
    available: true,
  },
  {
    id: 'vol-002',
    name: 'Jenna M. (Ham Radio, Civil Defence)',
    skills: ['Comms', 'Logistics', 'Hindi/English'],
    coords: { x: 66, y: 52 },
    distanceMiles: 1.0,
    available: true,
  },
  {
    id: 'vol-003',
    name: 'Marcus T. (NDRF Reserve, 4WD)',
    skills: ['Transport', 'Heavy lifting', 'Swift-water rescue'],
    coords: { x: 30, y: 60 },
    distanceMiles: 0.7,
    available: false,
  },
];

const NCR_RESOURCES: Resource[] = [
  {
    id: 'res-001', type: 'hospital',
    name: 'AIIMS Trauma Centre',
    address: 'Sri Aurobindo Marg, Ansari Nagar',
    distanceMiles: 2.1, coords: { x: 14, y: 80 }, open24h: true,
    phone: '+91 11 2659 4404',
    tags: ['Emergency', 'Trauma', 'ICU', 'Dialysis'], status: 'open',
  },
  {
    id: 'res-002', type: 'hospital',
    name: 'LNJP Hospital',
    address: 'Bahadur Shah Zafar Marg, Delhi Gate',
    distanceMiles: 0.9, coords: { x: 42, y: 40 }, open24h: true,
    phone: '+91 11 2323 1740',
    tags: ['Emergency', 'Pediatrics', 'Maternity'], status: 'limited',
  },
  {
    id: 'res-003', type: 'hospital',
    name: 'GTB Hospital',
    address: 'Dilshad Garden, Shahdara',
    distanceMiles: 1.7, coords: { x: 72, y: 22 }, open24h: true,
    phone: '+91 11 2259 1669',
    tags: ['Emergency', 'Trauma', 'Orthopedics'], status: 'open',
  },
  {
    id: 'res-004', type: 'hospital',
    name: 'Max Super Speciality, Patparganj',
    address: '108A, IP Extension, Patparganj',
    distanceMiles: 1.3, coords: { x: 60, y: 28 }, open24h: true,
    phone: '+91 11 2212 1111',
    tags: ['Emergency', 'ICU', 'Private'], status: 'open',
  },
  {
    id: 'res-005', type: 'pharmacy',
    name: 'Apollo Pharmacy, Mayur Vihar',
    address: 'Pocket 4, Mayur Vihar Phase I',
    distanceMiles: 0.5, coords: { x: 30, y: 52 }, open24h: false,
    phone: '+91 11 2279 1234',
    tags: ['Insulin', 'Oxygen', 'Prescription'], status: 'open',
  },
  {
    id: 'res-006', type: 'pharmacy',
    name: 'Guardian Pharmacy, Geeta Colony',
    address: 'Main Road, Geeta Colony',
    distanceMiles: 0.8, coords: { x: 46, y: 64 }, open24h: false,
    phone: '+91 11 2235 5678',
    tags: ['General', 'Baby care', 'First aid'], status: 'limited',
  },
  {
    id: 'res-007', type: 'food',
    name: 'ISKCON Food Relief Camp',
    address: 'ISKCON Temple, Sant Nagar, East of Kailash',
    distanceMiles: 1.5, coords: { x: 20, y: 82 }, open24h: true,
    phone: '+91 11 2624 4400',
    tags: ['Hot meals', 'Vegetarian', 'Free'], status: 'open',
  },
  {
    id: 'res-008', type: 'food',
    name: 'Gurudwara Bangla Sahib Community Kitchen',
    address: 'Connaught Place, Baba Kharak Singh Marg',
    distanceMiles: 1.2, coords: { x: 52, y: 44 }, open24h: true,
    phone: '+91 11 2584 4078',
    tags: ['Hot meals', 'Langar', 'Free', 'All welcome'], status: 'open',
  },
  {
    id: 'res-009', type: 'food',
    name: 'Delhi Govt Relief — Yamuna Pushta',
    address: 'Yamuna Pushta, Civil Lines',
    distanceMiles: 0.6, coords: { x: 38, y: 30 }, open24h: false,
    phone: '1077 (Helpline)',
    tags: ['Water', 'ORS', 'Ration kit'], status: 'open',
  },
  {
    id: 'res-010', type: 'shelter',
    name: 'Rajkiya Sarvodaya Bal Vidyalaya',
    address: 'Pocket 1, Mayur Vihar Phase I',
    distanceMiles: 0.4, coords: { x: 28, y: 50 }, open24h: true,
    phone: '+91 11 2275 1100',
    tags: ['Pet-friendly', 'Accessible', 'Medical staff'], status: 'open', bedsAvailable: 15,
  },
  {
    id: 'res-011', type: 'shelter',
    name: 'Chhatrasal Stadium',
    address: 'Model Town, North Delhi',
    distanceMiles: 1.8, coords: { x: 16, y: 36 }, open24h: true,
    phone: '+91 11 2745 2200',
    tags: ['Large capacity', 'Medical staff', 'Showers'], status: 'open', bedsAvailable: 66,
  },
  {
    id: 'res-012', type: 'rescue',
    name: 'NDRF Command Post — Wazirabad Barrage',
    address: 'Wazirabad Barrage, Civil Lines',
    distanceMiles: 1.9, coords: { x: 22, y: 70 }, open24h: true,
    phone: '011-2343 8000',
    tags: ['Boat rescue', 'Swift-water', 'Evacuation'], status: 'open',
  },
  {
    id: 'res-013', type: 'rescue',
    name: 'Civil Defence Volunteer Hub — ITO',
    address: 'ITO, Bahadur Shah Zafar Marg',
    distanceMiles: 1.0, coords: { x: 38, y: 48 }, open24h: true,
    phone: '1077 (Helpline)',
    tags: ['Transport', 'Sandbagging', 'Last-mile delivery'], status: 'open',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// CHAMOLI / JOSHIMATH — UTTARAKHAND
// ─────────────────────────────────────────────────────────────────────────────

const CHAMOLI_REQUESTS: AidRequest[] = [
  {
    id: 'ch-req-001',
    category: 'rescue',
    priority: 'critical',
    status: 'active',
    title: 'Family stranded by landslide — Selang Village, NH-7',
    details: 'NH-7 blocked by debris near Selang. Family of 5 cut off — no road access. Requesting helicopter or rope evacuation. Children present.',
    items: ['Helicopter evacuation', 'Rope rescue team', 'Food & water (2 days)', 'Warm clothing'],
    contactName: 'Suresh Negi',
    contactPhone: '+91 94xxx xx301',
    distanceMiles: 1.2,
    createdAt: now - 8 * min,
    coords: { x: 34, y: 56 },
    peopleCount: 5,
  },
  {
    id: 'ch-req-002',
    category: 'medical',
    priority: 'critical',
    status: 'active',
    title: 'Altitude sickness (HACE) — trekker near Ghangaria',
    details: 'Tourist from Pune showing signs of High Altitude Cerebral Edema. Unconscious, needs immediate helicopter evacuation to Joshimath CHC.',
    items: ['Helicopter medevac', 'Dexamethasone injection', 'Oxygen cylinder', 'Stretcher'],
    contactName: 'Guide Mohan Lal',
    contactPhone: '+91 94xxx xx408',
    distanceMiles: 2.8,
    createdAt: now - 22 * min,
    coords: { x: 58, y: 38 },
    peopleCount: 1,
  },
  {
    id: 'ch-req-003',
    category: 'food',
    priority: 'urgent',
    status: 'active',
    title: 'Food and water for 35 stranded pilgrims — Govindghat',
    details: '35 pilgrims returning from Badrinath stranded at Govindghat camp. Road washed out. Supplies running out after 2 days.',
    items: ['Cooked meals (35×)', 'Bottled water (50L)', 'ORS sachets', 'Blankets'],
    contactName: 'Gurudwara Govindghat Sevadar',
    contactPhone: '+91 94xxx xx512',
    distanceMiles: 1.9,
    createdAt: now - 45 * min,
    coords: { x: 46, y: 66 },
    peopleCount: 35,
  },
  {
    id: 'ch-req-004',
    category: 'shelter',
    priority: 'urgent',
    status: 'active',
    title: 'Emergency shelter for 18 displaced families — Joshimath Lower Ward',
    details: 'Subsidence cracks in homes at Manohar Bagh. 18 families asked to vacate. Currently in the open. Need interim shelter urgently.',
    items: ['Tents / temporary shelter', 'Sleeping bags', 'Cooking gas', 'Baby food'],
    contactName: 'Panchayat Head Kavita Rawat',
    contactPhone: '+91 94xxx xx617',
    distanceMiles: 0.3,
    createdAt: now - 1.1 * hr,
    coords: { x: 52, y: 44 },
    peopleCount: 72,
  },
  {
    id: 'ch-req-005',
    category: 'volunteers',
    priority: 'moderate',
    status: 'active',
    title: 'Volunteers for debris clearance — Tapovan approach road',
    details: 'BRO machinery unavailable. Need 15 able-bodied volunteers with shovels to clear rockfall from Tapovan road. ITBP will supervise.',
    items: ['Volunteers (15+)', 'Shovels', 'Pickaxes', 'Safety helmets', 'Gloves'],
    contactName: 'Naik Deepak Singh (ITBP)',
    contactPhone: '+91 94xxx xx723',
    distanceMiles: 2.1,
    createdAt: now - 2.5 * hr,
    coords: { x: 28, y: 72 },
    peopleCount: 0,
  },
  {
    id: 'ch-req-006',
    category: 'medical',
    priority: 'urgent',
    status: 'active',
    title: 'Fracture patient needs evacuation — Pandukeshwar',
    details: 'Villager fell on slippery slope. Suspected femur fracture. CHC Joshimath 12km away but road blocked. Needs stretcher + vehicle.',
    items: ['Stretcher with straps', '4WD vehicle or mule evacuation', 'Splint', 'Painkiller (IV)'],
    contactName: 'Anita Prasad',
    contactPhone: '+91 94xxx xx831',
    distanceMiles: 2.4,
    createdAt: now - 35 * min,
    coords: { x: 62, y: 30 },
    peopleCount: 1,
  },
  {
    id: 'ch-req-007',
    category: 'food',
    priority: 'moderate',
    status: 'active',
    title: 'Dry rations for 10 families cut off at Dungri',
    details: 'Khiro Gad flash flood blocked the only path to Dungri village. 10 families with elderly and children. Water supply also affected.',
    items: ['Rice (50 kg)', 'Dal (20 kg)', 'Oil (10L)', 'Salt & spices', 'Water purification tablets'],
    contactName: 'Ramkishore Bisht',
    contactPhone: '+91 94xxx xx940',
    distanceMiles: 1.6,
    createdAt: now - 1.8 * hr,
    coords: { x: 70, y: 52 },
    peopleCount: 38,
  },
  {
    id: 'ch-req-008',
    category: 'rescue',
    priority: 'urgent',
    status: 'active',
    title: 'Missing trekkers — Valley of Flowers trail',
    details: '3 trekkers from Gujarat overdue by 24 hours on VOF trail. Last GPS ping near Bhyundar. SDRF search party requested.',
    items: ['SDRF search team', 'Thermal drone', 'First aid kit', 'Satellite communicator'],
    contactName: 'Trek Coordinator Vijay Kumar',
    contactPhone: '+91 94xxx xx055',
    distanceMiles: 3.1,
    createdAt: now - 3 * hr,
    coords: { x: 76, y: 24 },
    peopleCount: 3,
  },
];

const CHAMOLI_SHELTERS: Shelter[] = [
  {
    id: 'ch-shelter-001',
    name: 'ITBP Camp — Joshimath',
    address: 'ITBP Campus, Upper Joshimath, Chamoli',
    capacity: 500,
    occupied: 180,
    coords: { x: 52, y: 28 },
    amenities: ['Helipad', 'Medical unit', 'Rations', 'Blankets', 'Radio comms', '24/7'],
    status: 'open',
  },
  {
    id: 'ch-shelter-002',
    name: 'Govt Inter College — Joshimath',
    address: 'Upper Market Area, Joshimath, Chamoli',
    capacity: 300,
    occupied: 220,
    coords: { x: 44, y: 46 },
    amenities: ['Accessible', 'Hot meals (Gurudwara Govindghat)', 'Toilets', 'Water supply'],
    status: 'open',
  },
  {
    id: 'ch-shelter-003',
    name: 'Narsingh Temple Dharamshala',
    address: 'Near Narsingh Temple, Upper Joshimath',
    capacity: 150,
    occupied: 90,
    coords: { x: 48, y: 38 },
    amenities: ['Kitchen', 'Blankets', 'Safe elevation', 'Prayers'],
    status: 'open',
  },
  {
    id: 'ch-shelter-004',
    name: 'Auli GMVN Rest House',
    address: 'Auli Ski Resort Area, 2,519 m altitude',
    capacity: 120,
    occupied: 30,
    coords: { x: 36, y: 20 },
    amenities: ['Generator', 'Heating', 'Blankets', 'Meals', 'Away from slide zones'],
    status: 'open',
  },
  {
    id: 'ch-shelter-005',
    name: 'Badrinath Dham Guest House',
    address: 'Badrinath Temple Trust, Badrinath, 3,133 m',
    capacity: 200,
    occupied: 40,
    coords: { x: 80, y: 30 },
    amenities: ['Pilgrimage support', 'Meals', 'Medical aid station', 'Elevated safe zone'],
    status: 'open',
  },
];

const CHAMOLI_VOLUNTEERS: Volunteer[] = [
  {
    id: 'ch-vol-001',
    name: 'Sub-Inspector Deepak Rana (SDRF)',
    skills: ['Rope rescue', 'Swift-water', 'First aid', 'Night ops'],
    coords: { x: 44, y: 50 },
    distanceMiles: 0.4,
    available: true,
  },
  {
    id: 'ch-vol-002',
    name: 'Dr. Shivani Bisht (CHC Joshimath)',
    skills: ['Emergency medicine', 'AMS/HACE/HAPE', 'Triage', 'Oxygen therapy'],
    coords: { x: 54, y: 40 },
    distanceMiles: 0.6,
    available: true,
  },
  {
    id: 'ch-vol-003',
    name: 'Naik Surender Kumar (ITBP)',
    skills: ['Mountain rescue', 'Helicopter ops', 'Logistics', 'Communications'],
    coords: { x: 40, y: 32 },
    distanceMiles: 0.8,
    available: true,
  },
  {
    id: 'ch-vol-004',
    name: 'Ganesh Rawat (BRO Operator)',
    skills: ['Road clearing', 'Heavy machinery (JCB)', 'Route assessment'],
    coords: { x: 36, y: 58 },
    distanceMiles: 1.1,
    available: false,
  },
];

const CHAMOLI_RESOURCES: Resource[] = [
  {
    id: 'ch-res-001', type: 'hospital',
    name: 'CHC Joshimath (Community Health Centre)',
    address: 'Lower Market, Joshimath, Chamoli',
    distanceMiles: 0.3, coords: { x: 50, y: 50 }, open24h: true,
    phone: '01389-222016',
    tags: ['Emergency OPD', 'Oxygen', 'X-Ray', 'Ambulance', 'AMS treatment'],
    status: 'open',
  },
  {
    id: 'ch-res-002', type: 'hospital',
    name: 'ITBP Medical Unit — Joshimath',
    address: 'ITBP Camp, Upper Joshimath',
    distanceMiles: 0.6, coords: { x: 52, y: 28 }, open24h: true,
    phone: '01389-222001',
    tags: ['Trauma care', 'HACE/HAPE', 'Surgery', 'Helicopter evacuation'],
    status: 'open',
  },
  {
    id: 'ch-res-003', type: 'hospital',
    name: 'First Aid Post — Govindghat',
    address: 'Govindghat, NH-7, Chamoli',
    distanceMiles: 1.9, coords: { x: 46, y: 70 }, open24h: false,
    phone: '01381-222200',
    tags: ['First aid', 'AMS response', 'Stretcher relay'],
    status: 'open',
  },
  {
    id: 'ch-res-004', type: 'hospital',
    name: 'PHC Badrinath',
    address: 'Near Badrinath Temple, Chamoli',
    distanceMiles: 6.2, coords: { x: 80, y: 30 }, open24h: false,
    phone: '01381-222108',
    tags: ['First aid', 'Oxygen', 'Basic medicines'],
    status: 'open',
  },
  {
    id: 'ch-res-005', type: 'pharmacy',
    name: 'Jan Aushadhi Kendra — Joshimath',
    address: 'Upper Market, Joshimath',
    distanceMiles: 0.4, coords: { x: 50, y: 44 }, open24h: false,
    phone: '01389-222060',
    tags: ['Generic medicines', 'AMS drugs', 'Bandages', 'ORS'],
    status: 'open',
  },
  {
    id: 'ch-res-006', type: 'food',
    name: 'Gurudwara Govindghat — Community Langar',
    address: 'Govindghat, Chamoli',
    distanceMiles: 1.9, coords: { x: 46, y: 70 }, open24h: true,
    phone: '01381-222200',
    tags: ['Free meals', 'All welcome', 'Pilgrims', 'Flood victims'],
    status: 'open',
  },
  {
    id: 'ch-res-007', type: 'food',
    name: 'NDRF Relief Kitchen — Joshimath',
    address: 'NDRF Camp, Near Bus Stand, Joshimath',
    distanceMiles: 0.5, coords: { x: 48, y: 54 }, open24h: false,
    phone: '01372-252700',
    tags: ['Hot meals', 'Water', 'Dry rations', 'Disaster victims only'],
    status: 'open',
  },
  {
    id: 'ch-res-008', type: 'food',
    name: 'State Govt Relief Distribution — Joshimath',
    address: 'SDM Office Campus, Joshimath',
    distanceMiles: 0.4, coords: { x: 50, y: 48 }, open24h: false,
    phone: '01389-222010',
    tags: ['Ration kits', 'Water cans', 'Baby food', 'ORS'],
    status: 'open',
  },
  {
    id: 'ch-res-009', type: 'shelter',
    name: 'ITBP Camp Shelter — Joshimath',
    address: 'ITBP Campus, Upper Joshimath',
    distanceMiles: 0.6, coords: { x: 52, y: 28 }, open24h: true,
    phone: '01389-222001',
    tags: ['Helipad', 'Medical unit', 'Blankets', 'Radio comms'],
    status: 'open', bedsAvailable: 320,
  },
  {
    id: 'ch-res-010', type: 'shelter',
    name: 'Govt Inter College Relief Camp',
    address: 'Upper Market, Joshimath, Chamoli',
    distanceMiles: 0.3, coords: { x: 44, y: 46 }, open24h: true,
    phone: '01389-222050',
    tags: ['Accessible', 'Hot meals', 'Toilets', 'Water'],
    status: 'open', bedsAvailable: 80,
  },
  {
    id: 'ch-res-011', type: 'rescue',
    name: 'SDRF Post — Joshimath',
    address: 'Near Police Station, Joshimath',
    distanceMiles: 0.5, coords: { x: 46, y: 50 }, open24h: true,
    phone: '01389-222030',
    tags: ['Rope rescue', 'Boat', 'Night ops', 'Landslide response'],
    status: 'open',
  },
  {
    id: 'ch-res-012', type: 'rescue',
    name: 'NDRF Forward Post — Pipalkoti',
    address: 'NH-7, Pipalkoti, Chamoli (30km from Joshimath)',
    distanceMiles: 3.0, coords: { x: 24, y: 74 }, open24h: true,
    phone: '01372-252700',
    tags: ['Rescue teams', 'Medical support', 'Comms equipment'],
    status: 'open',
  },
  {
    id: 'ch-res-013', type: 'rescue',
    name: 'Helipad — ITBP Joshimath',
    address: 'ITBP Camp, Joshimath',
    distanceMiles: 0.6, coords: { x: 52, y: 26 }, open24h: true,
    phone: '01389-222001',
    tags: ['Helicopter medevac', 'Casualty evacuation', 'Supply drops'],
    status: 'open',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// REGION DATA MAP — single source of truth, keyed by region
// ─────────────────────────────────────────────────────────────────────────────
export const REGION_DATA: Record<RegionKey, {
  requests:   AidRequest[];
  shelters:   Shelter[];
  volunteers: Volunteer[];
  resources:  Resource[];
  locationLabel: string; // used in Directions button
}> = {
  ncr: {
    requests:      NCR_REQUESTS,
    shelters:      NCR_SHELTERS,
    volunteers:    NCR_VOLUNTEERS,
    resources:     NCR_RESOURCES,
    locationLabel: 'Delhi NCR',
  },
  badrinath: {
    requests:      CHAMOLI_REQUESTS,
    shelters:      CHAMOLI_SHELTERS,
    volunteers:    CHAMOLI_VOLUNTEERS,
    resources:     CHAMOLI_RESOURCES,
    locationLabel: 'Chamoli, Uttarakhand',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Legacy flat exports (kept for backward compat — always NCR)
// ─────────────────────────────────────────────────────────────────────────────
export const MOCK_REQUESTS  = NCR_REQUESTS;
export const MOCK_SHELTERS  = NCR_SHELTERS;
export const MOCK_VOLUNTEERS= NCR_VOLUNTEERS;
export const MOCK_RESOURCES = NCR_RESOURCES;

// ─────────────────────────────────────────────────────────────────────────────
// REGION META (heading, hazard, stats)
// ─────────────────────────────────────────────────────────────────────────────
export const EMERGENCY_ZONE = 'Yamuna Flood Relief — East Delhi NCR';

export const REGION_ZONES = {
  ncr: {
    zone:     'Yamuna Flood Relief — East Delhi NCR',
    location: 'Delhi · Noida · Gurugram · Faridabad · Ghaziabad',
    hazard:   'Active Flood Zone — Yamuna River Basin',
    stats:    { requestCount: NCR_REQUESTS.length, shelterCount: NCR_SHELTERS.length, responderCount: 13, area: 'NCR Region' },
  },
  badrinath: {
    zone:     'Disaster Relief — Joshimath, Chamoli, Uttarakhand',
    location: 'Joshimath · Badrinath · Chamoli District · Uttarakhand',
    hazard:   'Active Landslide & Flood Zone — Himalayan Region',
    stats:    { requestCount: CHAMOLI_REQUESTS.length, shelterCount: CHAMOLI_SHELTERS.length, responderCount: 7, area: 'Chamoli District' },
  },
} as const;
